x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow

  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor

    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
      postgresql+psycopg://airflow:airflow@airflow-postgres/airflow

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"

    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: >-
      http://airflow-apiserver:8080/execution/

    AIRFLOW__API_AUTH__JWT_SECRET: stock_airflow_dev_secret

    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "true"

    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"

    DB_HOST: host.docker.internal
    DB_PORT: "5435"
    DB_NAME: stock_dw
    DB_USER: postgres
    DB_PASSWORD: "1"

  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins

    - ./:/opt/airflow/project

    - ./.env.airflow:/opt/airflow/project/.env:ro

  working_dir: /opt/airflow/project

  extra_hosts:
    - "host.docker.internal:host-gateway"

  depends_on:
    airflow-postgres:
      condition: service_healthy


services:

  # ==========================================================
  # AIRFLOW METADATA DATABASE
  # Không expose port ra Windows
  # ==========================================================

  airflow-postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    volumes:
      - stock_airflow_postgres:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U airflow -d airflow"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped


  # ==========================================================
  # INITIALIZE AIRFLOW DB
  # ==========================================================

  airflow-init:
    <<: *airflow-common

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db migrate
        echo "Airflow metadata database initialized."


  # ==========================================================
  # API SERVER + UI
  #
  # Windows:
  # http://localhost:8081
  # ==========================================================

  airflow-apiserver:
    <<: *airflow-common

    command: api-server

    ports:
      - "8081:8080"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/api/v2/monitor/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s

    depends_on:
      airflow-postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    restart: unless-stopped


  # ==========================================================
  # SCHEDULER
  # ==========================================================

  airflow-scheduler:
    <<: *airflow-common

    command: scheduler

    depends_on:
      airflow-postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

      airflow-apiserver:
        condition: service_healthy

    restart: unless-stopped


  # ==========================================================
  # DAG PROCESSOR
  # ==========================================================

  airflow-dag-processor:
    <<: *airflow-common

    command: dag-processor

    depends_on:
      airflow-postgres:
        condition: service_healthy

      airflow-init:
        condition: service_completed_successfully

    restart: unless-stopped


volumes:

  stock_airflow_postgres: